Migrate ZSTD Codec and dependency
ome/ome-codecs pull request #22
Opened 2022-10-06 11:59 UTC by dgault

Adds the ZSTD Codec and associated aircompressor dependency. These are currently located in formats-bsd and in use for CZI and Tiff formats.

The only small code change from the original is to change FormatExceptions to CodecExceptions to match the behaviour of the existing codecs in this repo. A bioformats PR removing the dependency and implementation will follow.

2022-10-06 13:13 UTC, sbesson requested changes
I'll try and look a bit more in details today but two immediate comments:

- the new class is lacking standard license boilerplate.
- the code formatting does not follow the [Bio-Formats convention](https://docs.openmicroscopy.org/bio-formats/6.10.1/developers/code-formatting.html) 

Also how easy would it be to include a minimal decompression unit test to ensure some functional testing at the level of this repository?

2022-10-06 19:08 UTC, melissalinkert requested changes

2022-10-06 19:08 UTC, melissalinkert commented on src/main/java/ome/codecs/ZstdCodec.java
> +  public byte[] decompress(byte[] data, int inputOffset, int length)
Javadoc comment would be nice here, since this doesn't override an existing API method.

2022-10-10 15:43 UTC, melissalinkert requested changes
This is fine with me once the last two nitpicky comments are addressed.

2022-10-10 15:43 UTC, melissalinkert commented on src/main/java/ome/codecs/ZstdCodec.java
> +    if (byteCount > Integer.MAX_VALUE || byteCount < Integer.MIN_VALUE)
`byteCount < 0` instead of `byteCount < Integer.MIN_VALUE`?

2022-10-10 15:43 UTC, melissalinkert commented on src/main/java/ome/codecs/ZstdCodec.java
> +      throw new CodecException("Integer overflow detected when calculating file byteCount.");
Enclosing this line in `{}` would be more in keeping with the current style.

2022-10-11 13:38 UTC, melissalinkert approved these changes

2022-10-11 13:59 UTC, merged